### ISSUE TITLE
Gist display line numbers not aligned with code

### ISSUE THREAD

**Issue by danwagnerco** [manovotny/wp-gist#37]
Love this project, couldn't be easier to use.

There appears to be an interesting shift between the line numbers and code on my first WP post. Here's a link to the gist itself, as well as the post:

* https://gist.github.com/danwagnerco/3821db6b9986bac030c2
* http://danwagner.co/create-a-new-column-based-on-a-different-column-with-vba/

Here's a screenshot of how it looks in Chrome:

![image](https://cloud.githubusercontent.com/assets/6598675/8042384/8b0f80ca-0de4-11e5-937a-616541096c3f.png)

I'm using version 3.0.0 of WP Gist, version 3.5.3 of JP Markdown and Wordpress 4.2.2 with the Highend theme.

What could be causing this alignment issue?

**Comment by manovotny** [comment]
Hey @danwagnerco!

So, it looks like the WP Gist styles cannot be found. This error is being thrown on your site.

![create_a_new_column_based_on_a_different_column_with_vba___dan_wagner](https://cloud.githubusercontent.com/assets/446260/8074503/07110b70-0ef9-11e5-899f-386bc2a9ec38.jpg)

This is most likely due to [this other issue](https://github.com/manovotny/wp-gist/issues/36). I am willing to bet that the WP Gist plugin folder isn't `wp-gist`, but probably `wp-gist-master`, since it was downloaded from GitHub and I can [locate the missing CSS file on your server there](http://danwagner.co/wp-content/plugins/wp-gist-master/css/style.min.css).

Two options are:

1. I can whip up a fix for that other issue here this week and you can update and everything will be great!
- Simply rename the folder on your server to `wp-gist` and the style should load correct. *Warning: You might have to reactivate the plugin after the rename*.

Let me know what you choose to do! I can try and carve out some time this week for Option 1, regardless.

**Comment by danwagnerco** [comment]
Hey @manovotny -- the second option worked like gangbusters. Thanks so much!

**Comment by manovotny** [comment]
@danwagnerco : : 

No sweat! Glad you're back up and running!
